name: Hello World Workflow
on: 
  push:
    branches:
      - main
jobs:
 blog_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - name : Set enviornment variables
        run : |
          echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Run script  
        env:
          HOST: ${{ secrets.HASHNODE_BLOG_NAME }}
          PAT: ${{ secrets.HASHNODE_API_KEY }}
          PUBID: ${{ secrets.HASHNODE_PUBLICATION_ID }}
          OWNER: ${{ env.OWNER }}
          REPO: ${{ env.REPO }}
          COHERE: ${{ secrets.COHERE_API_KEY }}

        run: node hashnode-blog.js
